### PR TITLE
python 3 update

### PR DESCRIPTION
**Pull request by jctt1983**
#5 Move the code to make it compatible with python 3.X, and upgrade the list of dependencies that can work with Python 3.X.

### CODE REVIEW

**Comment by gabriel-tessier** [comment]
I made some update essentially in the doc... I get some problem installing 3.6 version as it's no more supported in kubuntu package. They support from 3.7 but if we go with more large support and start from 3.6 here the resources to install 3.6. 
I add it in the readme, I also set the version 3.7, 3.8 in travis. 
I will push later as I didn't finish to review all things.

https://askubuntu.com/questions/865554/how-do-i-install-python-3-6-using-apt-get

**Comment by gabriel-tessier** [comment]
I pushed some fixes (for me) I stopped on this error on my local:

```
Traceback (most recent call last):
  File "wsgi.py", line 3, in <module>
    from app import app, socketio
  File "/home/gab/dev/HeadsUp/app/__init__.py", line 110, in <module>
    import app.filters  # noqa
  File "/home/gab/dev/HeadsUp/app/filters/__init__.py", line 3, in <module>
    from . import setup
  File "/home/gab/dev/HeadsUp/app/filters/setup.py", line 10, in <module>
    @app.app.context_processor
AttributeError: module 'app' has no attribute 'context_processor'

```

Travis build with 3.6 pass but 3.7 and 3.8 fail.

**Comment by jctt1983** [comment]
Ok I will install Python 3.7 and Python 3.8 in my distro to spot the errors... I'm sure is one library that is outdated
